### ISSUE TITLE
vi key bindings for command-line editing

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-community/utop#136]
some potential users would be interested by vi key bindings for command-line editing

**Comment by sjfloat** [comment]
+1

**Comment by nilsbecker** [comment]
see also upstream issue https://github.com/diml/lambda-term/issues/13

**Comment by lehmacdj** [comment]
Vi keybindings would make this much better in my opinion.

**Comment by xyproto** [comment]
As a workaround, `c-x c-e` for launching an external editor works here for editing lines in actual ViM.

**Comment by nilsbecker** [comment]
thx, it's a workaround but not a satisfying one -- speed and ease of editing short pieces of code matter.

**Comment by kandu** [comment]
@UnixJunkie and guys, I think we can clarify what you're expecting first since there are several modes in vi and the vi operator sequence are not simply key-bindings. They are all state machines. For example, to perform `2d2fi` on `a i b i c i d i e` will delete `a i b i c i d i`. You won't like to bind 2d2fi  4dfi d2fi dfi....(infinite combinations) in LTerm_read_line.

There is a key-binding facility provided by lambda-term currently

https://github.com/ocaml-community/lambda-term/blob/387c1c1b9b686568751eb22870b19d0df47edee0/src/lTerm_read_line.mli#L92
You can `bind` and `unbind` key sequence to some actions as you need.

I'm not sure but if it's not really competent for what you need, I think it's time to introduce some new facility to lambda-term and then we also adapt utop to gear-occlude them.

**Comment by lehmacdj** [comment]
Ideally, vi keybindings comparable to support in [readline*](http://man7.org/linux/man-pages/man3/readline.3.html), [zle](http://zsh.sourceforge.net/Guide/zshguide04.html) or [haskeline](https://github.com/judah/haskeline/wiki/KeyBindings#vi-specific-bindings) would be preferable.

All of these implement line editing via a state machine, and supporting a full range of common vi verbs (`d`, `c`, `y`, `p`, `i`, `A`, ...), and motions (`w`, `e`, `h`, `j`, `k`, `l`, ...). Beyond this readline and haskeline support very little, but zle, zsh's line editor also supports text objects (`i)`, `aw`, ...) as arguments to verbs.

To match these other line editors' feature sets lambda-term would need to implement interchangeable keymaps and allow keybindings to transition between them. This allows implementing the state machine. 

 I don't know what implementation other line editors use, but having a stack of keymaps that can pass information between them might be necessary to implement motions as arguments to commands without having to duplicate the keymaps (i.e. allow `d` and `c` to both transition to the same `keymap-motion` and after a motion is recognized pop that keymap and process the verb with the result from that keymap).

*: you can find a description on the readline(3) man page by searching "VI mode bindings"

**Comment by kandu** [comment]
ok, then, what about the existing key-bindings we are already accustomed with? And what about cooperating with the user-custom key-bindings defined with the current facility?

My proposal is, when in vi-insert mode, we dump all key input except 'esc' to the original binding-resolver, and we add a new key-binding <C-[> to switch back to vi-normal mode. That way, while in vi-insert mode, we can use some existing cute emacs style key-bindings and we'll benefit from the new vi-normal and vi-visual mode in addition. Certainly, this comes with cons, that we can't define modal operator-sequence in vi-insert mode(in fact, there is no vi-insert mode, it's just the current editing mode with an `esc` watch dog)

Or maybe we can implement a full vi-insert mode and cherry pick some existing key-bindings to the new vi-insert mode. But, any way, it breaks the backward-compatibility.

What's your opinion, dear all?

**Comment by kandu** [comment]
> it breaks the backward-compatibility

It doesn't mean that we'll drop support for the original editing mode. We'll have a new vi-insert mode, in which lambda-term can't inherit and benefit from the existing key-binding facility, though we can re-implement almost all the pre-defined key-bindings in the new mode

pre-defined key-bindings:
* https://github.com/ocaml-community/lambda-term/blob/387c1c1b9b686568751eb22870b19d0df47edee0/src/lTerm_read_line.ml#L183
* https://github.com/ocaml-community/lambda-term/blob/387c1c1b9b686568751eb22870b19d0df47edee0/src/lTerm_edit.ml#L101

**Comment by pmetzger** [comment]
Just a note, maybe this discussion should all be on lambda-term and not here, given that it's a lambda-term issue?

And although I'm an emacser, it does seem like having readline-like support for vi keybindings would be good.

**Comment by lehmacdj** [comment]
> We'll have a new vi-insert mode, in which lambda-term can't inherit and benefit from the existing key-binding facility, though we can re-implement almost all the pre-defined key-bindings in the new mode
Does this mean that it will not be possible to configure key bindings in vi-insert mode manually at all?

**Comment by lehmacdj** [comment]
It seems like what we want is to have multiple modes each of which is associated with its own Bindings module: https://github.com/ocaml-community/lambda-term/blob/387c1c1b9b686568751eb22870b19d0df47edee0/src/lTerm_edit.ml#L94

We then need to introduce an action to transition between active Bindings modules here: https://github.com/ocaml-community/lambda-term/blob/387c1c1b9b686568751eb22870b19d0df47edee0/src/lTerm_edit.ml#L22
Note that this would require using first class modules, to resolve keyboard input.

**Comment by kandu** [comment]
@pmetzger on lambda-term, we'll hear opinions mostly come from the developers, and here is a good place to hear from the end-users in addition :)

@lehmacdj
> Does this mean that it will not be possible to configure key bindings in vi-insert mode manually at all?

It depends. If we implement the mode with recursive descent functions, which is hard-coded, no, it is unlikely possible.

But we can implement it with a dynamic state machine. Just like a regexp engine, every time a new `imap` command is accepted, we join it to the existing key-map graph, recompile the graph to DFA. Yeah, we'll also implement the vi-command mode, too.

What about this roadmap: we write some recursive descent functions which is quite comfortable and quick to write, leave the vi-command mode unimplemented, to implement a minimum version first. Then we can hear some feedback and suggestions and then we release the second version which will come with a cute state machine and the vi-command mode.

**Comment by pmetzger** [comment]
@kandu I'm not as good at judging this as @diml might be. That said, do you have a specific design in mind?

**Comment by diml** [comment]
I only know the basics of vi, but a state machine does sound right.

**Comment by oblitum** [comment]
Not sure whether the same can be done here, but, in R REPL for example, it simply seems to leave this task to readline, if one wants to have vi-mode in R one just puts `set editing-mode vi` in `~/.inputrc`.

**Comment by nilsbecker** [comment]
>  in R REPL for example, it simply seems to leave this task to readline, if one wants to have vi-mode in R one just puts `set editing-mode vi` in `~/.inputrc`.

I'm not an expert by any means but I think it doesn't work that way in utop -- i think lambda-term interacts with key input on a lower level, to do completions etc, without using readline. in pure ocaml toplevel, `rlwrap ocaml' works (vi bindings if configured) but that also does not well with utop.

**Comment by kandu** [comment]
![utop](https://user-images.githubusercontent.com/357626/78748557-e743df00-799e-11ea-814f-c17ff56c2945.gif)

I created a new project to support general modal editing, and based on which, I also created a vi-specialied interpreter, and insert the interpreter layer between lambda-term and zed.

All the original keybindings, completion of utop, lambda-term are still work, it's now a perfect combination of the original emacs-like keybindings plus vim modal editing.

**Comment by kandu** [comment]
There is such a situation in vi, after we map both 'aa' and 'aaa' to some actions, the vi interpreter will not do the associated action instantly when you just type 'aa', it will wait for the potential third 'a' for a short time.

The project supporting general modal editing implemented such a mechanism.

Therefore, they're not simply reaction systems reacting on events. The inputting and interpreting process are multithreading.

Since LTerm_read_line is somewhat an individual component in lambda-term, and the two new projects are implement-independent (lwt, async, threads, keyboard code..) some small remould will gear-occlude them together.

But it still breaks backward-compatibility a bit. We're entering the lambda-term 3, zed 3 era.

I'm now looking at LTerm_edit, LTerm_widget, LTerm_widget_base modules, they are basic, fundamental components of many up-level ones. To remould them will take some extra time.

In my opinion, although we can release a bundle of new versions of utop, lambda-term 3, zed 3 right now. We better be patient for a while, since to break backward-compatibility twice in a very short period of time is not polite.

But if someone wants vi-enabled utop anxiously, I can release an experimental version first. In addition, early wider testing and feedback really help a lot.

**Comment by nilsbecker** [comment]
i would be happy to do some testing of an experimental vi enabled utop

**Comment by kandu** [comment]
After remoulding the entire lambda-term from the ground up, I think it's not worth the candle. What we gain is a vi-enabled LTerm_edit.edit which is rarely used, and what we lose is the simplicity of the react system among lambda-term. In case we really need such a editor widget, we can specialize one, meanwhile, it can be LTerm_wdiget.t compatible, which means we can put it in a box widget, working with other widget together etc. if we implement it elaborately.

So I'm going to summit a bundle of PRs containing a smaller set of  the enhancements, i.e. some normal releases.

**Comment by kandu** [comment]
Here is the utop vi-mode preview version

```
opam repository add kandu git+https://github.com/kandu/opam-repo
opam install utop.2.5.0~
```
type in `#edit_mode_vi` do trigger the vi mode. Have fun ;)
Well, since it's just a WIP preview version, it's supposed to be not so fun. Once you encounter any glitch, give me a knock-knock.

And this PR https://github.com/ocaml-community/lambda-term/pull/85 records the progress of the vi mode in detail.

**Comment by kandu** [comment]
Hey, guys, after @nilsbecker's thorough testing, we concluded a feature list that will be implemented in the initial release. In another word, it's almost in feature-freeze phase now.

And you can give the pre-release versions a try:
```
opam update kandu
opam upgrade zed mew_vi lambda-term
```

Some behaviors(Paste) differ from vi for now, and [here](https://github.com/ocaml-community/lambda-term/pull/85#issuecomment-617631317) is the reason.
