### ISSUE TITLE
Support statically linked utop executable

### ISSUE THREAD

**Issue by hongchangwu** [ocaml-community/utop#285]
Currently the `utop` executable is always dynamic linked. This works well when distributed with opam. However there are situations where a statically linked version may be preferable,  such as deploying to cloud or non-standard locations without opam.

I propose we add a `configure` script that can optionally generate the additional `-custom` flag to force static linking when building the `utop` executable.

If this sounds reasonable, I can prepare a PR.

**Comment by diml** [comment]
I'd suggest to do this in Dune directly, then it would benefit all OCaml projects immediately.

**Comment by hongchangwu** [comment]
What is the Dune change you had in mind? Is it adding something to the Configurator?

**Comment by diml** [comment]
I was more thinking of a global setting to force all bytecode executable to be linked with custom.

**Comment by diml** [comment]
But actually, I just remembered that you can already do that easily: if we add `(mode byte)` to `src/top/dune`, then building `src/top/utop.exe` will produce a statically linked utop. Currently building `src/top/utop.exe` fails since the library cannot be compiled in native mode, so adding this field seems fine. I'm doing that now.

**Comment by diml** [comment]
Ok, so you can now do: `dune build src/top/utop.exe` to build a statically linked utop.

**Comment by hongchangwu** [comment]
Great, thanks! Is it worth considering making the `exe` ones the default?

**Comment by pmetzger** [comment]
I don't think it should be the default.
