### ISSUE TITLE
utop assumes utop-discover-phrase returns triplet

### ISSUE THREAD

**Issue by bluewww** [ocaml-community/utop#300]
This is not true when `tuareg-discover-phrase` is used as backend.

**Comment by bluewww** [comment]
Sorry wrong project

**Comment by pmetzger** [comment]
Have a look in https://github.com/ocaml-community/utop/tree/master/src/top — you will see `utop.el` is there. But do you have a patch to propose?

**Comment by bluewww** [comment]
I will wait for a resolution of this https://github.com/ocaml/tuareg/issues/218 before attempting a patch. Currently I only have some hacky workaround on my machine.

**Comment by rduplain** [comment]
https://github.com/ocaml/tuareg/issues/218 is resolved:

* utop expects a triple on its discover-phrase call.
* tuareg at one point returned a pair, but has since restored its `tuareg-discover-phrase` functionality to return a triple as utop expects.

No further action needed; issue can be closed. Thanks!

**Comment by bluewww** [comment]
Thanks for the work
