### ISSUE TITLE
regression with qualifying ()

### ISSUE THREAD

**Issue by emillon** [ocaml-community/utop#428]
An issue with this change just appeared: the `core` library redefine the `Unit` module but without re-exporting `()` thus:
```
open Core;;
1 + 1;;
```
fails with
```
Error: Unbound constructor Unit.()
```

_Originally posted by @Octachron in https://github.com/ocaml-community/utop/issues/418#issuecomment-1516386584_

**Comment by Octachron** [comment]
Using `Stdlib.Unit` seems indeed safer to me since `Stdlib` is a compilation unit name rather than a submodule name. Thus, theoretically only people using `-nostdlib` would be affected by the issue but:
- people using `-nostdlib -nopervasives` probably knows what they are doing
- utop's `-nostdlib` doesn't seem to work right now

**Comment by emillon** [comment]
I'll do that. I suppose it's possible to downgrade to just `()` if `-nostdlib` is passed. (in that case, I'm not sure how to disambiguate with a user-provided `()`)

**Comment by Octachron** [comment]
I don't think it is worth it to invest too much effort to handle the `-nostdlib` case. Looking at the code, it might be simpler to rewrite the code to avoid the need to construct ghost tree.
